name: Manual Approval
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  request-approval:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.approval.outputs.approved }}
    steps:
      - name: Manual Approval
        id: approval
        uses: trstringer/manual-approval@main
        with:
            secret: ${{ secrets.APPROVAL_GITHUB_TOKEN }}
            approvers: emmaashi
            minimum-approvals: 1
            issue-title: "Deploy request for amazing-labyrinth"
            issue-body: "Please approve or deny this deployment."
            exclude-workflow-initiator-as-approver: false
            target-repository: amazing-labyrinth-approvals
            target-repository-owner: emmaashi

  build-and-deploy:
    needs: request-approval
    runs-on: ubuntu-latest
    if: needs.request-approval.outputs.approved == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Building the project..."

      - name: Deploy
        run: |
          echo "Deploying the project..."
